BEGIN;

CREATE TABLE IF NOT EXISTS public.client
(
    id         bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    address    character varying(255) COLLATE pg_catalog."default",
    first_name character varying(255) COLLATE pg_catalog."default",
    last_name  character varying(255) COLLATE pg_catalog."default",
    phone      character varying(255) COLLATE pg_catalog."default",
    user_id    bigint,
    CONSTRAINT client_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.contractor
(
    id           bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    address      character varying(255) COLLATE pg_catalog."default",
    name         character varying(255) COLLATE pg_catalog."default",
    phone_number character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT contractor_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.contractor_purchase_list
(
    contractor_id    bigint NOT NULL,
    purchase_list_id bigint NOT NULL,
    CONSTRAINT uk_luwnq4ea3anc7ytkd3th6sxcb UNIQUE (purchase_list_id)
);

CREATE TABLE IF NOT EXISTS public.coworker
(
    id          bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fio         character varying(30) COLLATE pg_catalog."default",
    id_position bigint NOT NULL,
    CONSTRAINT coworker_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.coworker_order_list
(
    coworker_id   bigint NOT NULL,
    order_list_id bigint NOT NULL,
    CONSTRAINT uk_i44618w7bbdvong88xh3xyqu0 UNIQUE (order_list_id)
);

CREATE TABLE IF NOT EXISTS public.dish
(
    id    bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    price integer NOT NULL,
    title character varying(255) COLLATE pg_catalog."default",
    name  character varying(255) COLLATE pg_catalog."default",
    unit  character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT dish_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dish_in_order
(
    id           bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    address      character varying(255) COLLATE pg_catalog."default",
    date         character varying(255) COLLATE pg_catalog."default",
    phone_number character varying(255) COLLATE pg_catalog."default",
    sum          integer NOT NULL,
    menu_id      bigint  NOT NULL,
    CONSTRAINT dish_in_order_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dish_ingredient_in_the_composition_list
(
    dish_id                               bigint NOT NULL,
    ingredient_in_the_composition_list_id bigint NOT NULL,
    CONSTRAINT uk_edyab5gxilpvco2mgr78i2kw4 UNIQUE (ingredient_in_the_composition_list_id)
);

CREATE TABLE IF NOT EXISTS public.dish_menu_list
(
    dish_id      bigint NOT NULL,
    menu_list_id bigint NOT NULL,
    CONSTRAINT uk_n5x91dm2urabjulbp0hbjlmip UNIQUE (menu_list_id)
);

CREATE TABLE IF NOT EXISTS public.employee
(
    id         bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    first_name character varying(255) COLLATE pg_catalog."default",
    last_name  character varying(255) COLLATE pg_catalog."default",
    salary     integer NOT NULL,
    user_id    bigint,
    CONSTRAINT employee_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ingredient
(
    id   bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    unit character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT ingredient_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ingredient_in_the_composition
(
    id            bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    sum           integer NOT NULL,
    dish_id       bigint  NOT NULL,
    ingredient_id bigint  NOT NULL,
    CONSTRAINT ingredient_in_the_composition_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ingredient_ingredient_in_the_composition_list
(
    ingredient_id                         bigint NOT NULL,
    ingredient_in_the_composition_list_id bigint NOT NULL,
    CONSTRAINT uk_k4pb7l64ohctwhdygsvweb3a6 UNIQUE (ingredient_in_the_composition_list_id)
);

CREATE TABLE IF NOT EXISTS public.ingredient_purchase_list
(
    ingredient_id    bigint NOT NULL,
    purchase_list_id bigint NOT NULL,
    CONSTRAINT uk_ahqw3matpsel250luiqautvs1 UNIQUE (purchase_list_id)
);

CREATE TABLE IF NOT EXISTS public.menu
(
    id         bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date       character varying(255) COLLATE pg_catalog."default",
    price_dish double precision,
    dish_id    bigint NOT NULL,
    CONSTRAINT menu_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.menu_dish_in_order_list
(
    menu_id               bigint NOT NULL,
    dish_in_order_list_id bigint NOT NULL,
    CONSTRAINT uk_ku7ffoeykndid3tu2qkc2wwd1 UNIQUE (dish_in_order_list_id)
);

CREATE TABLE IF NOT EXISTS public.menu_order_list
(
    menu_id       bigint NOT NULL,
    order_list_id bigint NOT NULL,
    CONSTRAINT uk_f4nccscso87ewmtyrmu3rprtt UNIQUE (order_list_id)
);

CREATE TABLE IF NOT EXISTS public."order"
(
    id           bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    completed    boolean NOT NULL,
    date         timestamp without time zone,
    client_id    bigint,
    employee_id  bigint,
    data         character varying(255) COLLATE pg_catalog."default",
    sum          integer NOT NULL,
    table_number integer NOT NULL,
    "time"       character varying(255) COLLATE pg_catalog."default",
    coworker_id  bigint  NOT NULL,
    menu_id      bigint  NOT NULL,
    CONSTRAINT order_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_dish
(
    order_id bigint NOT NULL,
    dish_id  bigint NOT NULL,
    CONSTRAINT order_dish_pkey PRIMARY KEY (order_id, dish_id)
);

CREATE TABLE IF NOT EXISTS public."position"
(
    id            bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name_position character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT position_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.position_coworker_list
(
    position_id      bigint NOT NULL,
    coworker_list_id bigint NOT NULL,
    CONSTRAINT uk_c7djyditmmc79ho4w2afxcag3 UNIQUE (coworker_list_id)
);

CREATE TABLE IF NOT EXISTS public.purchase
(
    id             bigint           NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date           character varying(255) COLLATE pg_catalog."default",
    price          double precision NOT NULL,
    sum            integer,
    contractors_id bigint           NOT NULL,
    ingredient_id  bigint           NOT NULL,
    CONSTRAINT purchase_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.role
(
    id    bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT role_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    id         bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email      character varying(255) COLLATE pg_catalog."default",
    password   character varying(255) COLLATE pg_catalog."default",
    username   character varying(255) COLLATE pg_catalog."default",
    role_id    bigint,
    first_name character varying(255) COLLATE pg_catalog."default",
    last_name  character varying(255) COLLATE pg_catalog."default",
    role       character varying(255) COLLATE pg_catalog."default",
    status     character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT user_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_role
(
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    CONSTRAINT user_role_pkey PRIMARY KEY (user_id, role_id)
);

ALTER TABLE IF EXISTS public.client
    ADD CONSTRAINT fkmi4tlsbdbmn0myf9cejh82chh FOREIGN KEY (user_id)
        REFERENCES public."user" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.contractor_purchase_list
    ADD CONSTRAINT fkcx6vl9lb29utv6akk12s8hmne FOREIGN KEY (purchase_list_id)
        REFERENCES public.purchase (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uk_luwnq4ea3anc7ytkd3th6sxcb
    ON public.contractor_purchase_list (purchase_list_id);


ALTER TABLE IF EXISTS public.contractor_purchase_list
    ADD CONSTRAINT fkrjiav6k9ew45jcmhdgnfa3jdq FOREIGN KEY (contractor_id)
        REFERENCES public.contractor (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coworker
    ADD CONSTRAINT fkg1206d6dakiwpl4atd8wtsmk8 FOREIGN KEY (id_position)
        REFERENCES public."position" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coworker_order_list
    ADD CONSTRAINT fkftvxup17wg4c4cswic57ya9f FOREIGN KEY (order_list_id)
        REFERENCES public."order" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uk_i44618w7bbdvong88xh3xyqu0
    ON public.coworker_order_list (order_list_id);


ALTER TABLE IF EXISTS public.coworker_order_list
    ADD CONSTRAINT fkstjviwpl9wamibyy9oxaf0f2f FOREIGN KEY (coworker_id)
        REFERENCES public.coworker (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.dish_in_order
    ADD CONSTRAINT fk3fv9178toinunjrfu5cvy7h6g FOREIGN KEY (menu_id)
        REFERENCES public.menu (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.dish_ingredient_in_the_composition_list
    ADD CONSTRAINT fk7ye76br92imc4is2thguolkeq FOREIGN KEY (ingredient_in_the_composition_list_id)
        REFERENCES public.ingredient_in_the_composition (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uk_edyab5gxilpvco2mgr78i2kw4
    ON public.dish_ingredient_in_the_composition_list (ingredient_in_the_composition_list_id);


ALTER TABLE IF EXISTS public.dish_ingredient_in_the_composition_list
    ADD CONSTRAINT fkmdal7droxab0301j3ny1k9lso FOREIGN KEY (dish_id)
        REFERENCES public.dish (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.dish_menu_list
    ADD CONSTRAINT fkdwkdj6cvpo78f1pckeubrslxq FOREIGN KEY (dish_id)
        REFERENCES public.dish (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.dish_menu_list
    ADD CONSTRAINT fkmb8uqgh4lnofthdm8uk6lt3fd FOREIGN KEY (menu_list_id)
        REFERENCES public.menu (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uk_n5x91dm2urabjulbp0hbjlmip
    ON public.dish_menu_list (menu_list_id);


ALTER TABLE IF EXISTS public.employee
    ADD CONSTRAINT fkf5lkvqkqs89qdqluo4couya15 FOREIGN KEY (user_id)
        REFERENCES public."user" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ingredient_in_the_composition
    ADD CONSTRAINT fk3rixl6iebqajo4olrk4d8w1o7 FOREIGN KEY (dish_id)
        REFERENCES public.dish (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ingredient_in_the_composition
    ADD CONSTRAINT fklvmwkqnrv1r8blnd5b9syl2go FOREIGN KEY (ingredient_id)
        REFERENCES public.ingredient (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ingredient_ingredient_in_the_composition_list
    ADD CONSTRAINT fk2c20w4tlif03v52s8ocfbky5f FOREIGN KEY (ingredient_in_the_composition_list_id)
        REFERENCES public.ingredient_in_the_composition (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uk_k4pb7l64ohctwhdygsvweb3a6
    ON public.ingredient_ingredient_in_the_composition_list (ingredient_in_the_composition_list_id);


ALTER TABLE IF EXISTS public.ingredient_ingredient_in_the_composition_list
    ADD CONSTRAINT fknw4hvmv7k3hgxxf3gyf6c2ooy FOREIGN KEY (ingredient_id)
        REFERENCES public.ingredient (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ingredient_purchase_list
    ADD CONSTRAINT fk6ovc7j565u4euf60m5v7p8387 FOREIGN KEY (purchase_list_id)
        REFERENCES public.purchase (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uk_ahqw3matpsel250luiqautvs1
    ON public.ingredient_purchase_list (purchase_list_id);


ALTER TABLE IF EXISTS public.ingredient_purchase_list
    ADD CONSTRAINT fkkbvcgg3u9106u7kx0c29jqqdw FOREIGN KEY (ingredient_id)
        REFERENCES public.ingredient (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.menu
    ADD CONSTRAINT fkbm92hs82t812cdhtj0l0ok6kl FOREIGN KEY (dish_id)
        REFERENCES public.dish (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.menu_dish_in_order_list
    ADD CONSTRAINT fk7gd0nninflvjr0gdifsgcglmn FOREIGN KEY (menu_id)
        REFERENCES public.menu (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.menu_dish_in_order_list
    ADD CONSTRAINT fkf5clft22o12hdkcukun2tx4mk FOREIGN KEY (dish_in_order_list_id)
        REFERENCES public.dish_in_order (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uk_ku7ffoeykndid3tu2qkc2wwd1
    ON public.menu_dish_in_order_list (dish_in_order_list_id);


ALTER TABLE IF EXISTS public.menu_order_list
    ADD CONSTRAINT fk3wqvrpqupbpermkrerajkgt9l FOREIGN KEY (menu_id)
        REFERENCES public.menu (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.menu_order_list
    ADD CONSTRAINT fkah26fvt56ohkiu63rlrbivqgl FOREIGN KEY (order_list_id)
        REFERENCES public."order" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uk_f4nccscso87ewmtyrmu3rprtt
    ON public.menu_order_list (order_list_id);


ALTER TABLE IF EXISTS public."order"
    ADD CONSTRAINT fk98rwcthah9r6x9pfk63yqktmg FOREIGN KEY (coworker_id)
        REFERENCES public.coworker (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."order"
    ADD CONSTRAINT fkdjonorx78bdje2vp5oyrt0qrq FOREIGN KEY (employee_id)
        REFERENCES public.employee (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."order"
    ADD CONSTRAINT fkhqad2xyyn10pct9vramixbm8n FOREIGN KEY (client_id)
        REFERENCES public.client (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."order"
    ADD CONSTRAINT fkm0ds65ju5ysiu1avd3q3rgr41 FOREIGN KEY (menu_id)
        REFERENCES public.menu (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_dish
    ADD CONSTRAINT fk4135139pcj4onxcdpcwvspwt1 FOREIGN KEY (order_id)
        REFERENCES public.dish (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_dish
    ADD CONSTRAINT fkmve8iwyuqmx3k41mlg5o57exp FOREIGN KEY (dish_id)
        REFERENCES public."order" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.position_coworker_list
    ADD CONSTRAINT fk9799u6twogv44ipw1k7lw02v3 FOREIGN KEY (position_id)
        REFERENCES public."position" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.position_coworker_list
    ADD CONSTRAINT fkp93wn4x74h177b4g39201wmmc FOREIGN KEY (coworker_list_id)
        REFERENCES public.coworker (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uk_c7djyditmmc79ho4w2afxcag3
    ON public.position_coworker_list (coworker_list_id);


ALTER TABLE IF EXISTS public.purchase
    ADD CONSTRAINT fk9qia50ac0hxvjrcci27od8k2v FOREIGN KEY (ingredient_id)
        REFERENCES public.ingredient (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.purchase
    ADD CONSTRAINT fkr1m0yy7dkct9v0vno2a4q2vqk FOREIGN KEY (contractors_id)
        REFERENCES public.contractor (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."user"
    ADD CONSTRAINT fkdl9dqp078pc03g6kdnxmnlqpc FOREIGN KEY (role_id)
        REFERENCES public.role (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_role
    ADD CONSTRAINT fkbyr41afwb1tyy6ri6n9c1r0g FOREIGN KEY (role_id)
        REFERENCES public."user" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_role
    ADD CONSTRAINT fkdnjkp24v4kpfcj4lqniebkwym FOREIGN KEY (user_id)
        REFERENCES public.role (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;

END;