spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cafe
    username: mamedov
    password: mamedov
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace